algoritmo "Modelo de Procuração"
var
   nome, endereco: caractere
   cpf: inteiro

inicio
      escreval("Qual o seu nome? ")
      leia(nome)
      escreval("Qual o seu CPF? ")
      leia(cpf)
      escreval("Qual o seu endereço? ")
      leia(endereco)
      escreval("----------------")
      escreval("PROCURAÇÃO")
      escreval( nome, "inscrito no CPF: ", cpf, " residente no endereço: ", endereco, " por meio dessa procuração me dá poderes X, Y e Z blábláblá")
fimalgoritmo
